# Generated by Django 5.1.6 on 2025-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippineAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('municipality_city', models.TextField(blank=True, null=True)),
                ('barangay', models.TextField(blank=True, null=True)),
                ('postal', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='ph_region_idx'), models.Index(fields=['province'], name='ph_province_idx'), models.Index(fields=['municipality_city'], name='ph_municipality_city_idx'), models.Index(fields=['barangay'], name='ph_barangay_idx')],
            },
        ),
    ]
