"""
Django settings for philippian_encoder project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(",")


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://redis:6379/0")

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_celery_beat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'addresses',
    'pancake',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pancake.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'philippian_encoder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'philippian_encoder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('','django.db.backends.postgresql'),
        'NAME': os.environ.get('POSTGRES_NAME', 'pgoc'),
        'USER': os.environ.get('POSTGRES_USER', 'pgoc'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'admin_pgoc2024'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://redis:6379/0")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = 'Asia/Manila'
CELERY_ENABLE_UTC = False



# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jaysoncanete.pgoc@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'nlgurrtvsnyteghy'  # Use an app password or environment variable




JAZZMIN_SETTINGS = {
    ############
    # Top Menu #
    ############
    # Welcome text on the login screen
    "welcome_sign": "Philippian Encoder System (PhEnSys)",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    # "login_logo": 'logo/small-pgoc-logo3.png',

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    # "site_icon": 'logo/favicon-pgoc-circlewhite.ico',

    # Logo to use for your site, must be present in static files, used for brand on top left
    # "site_logo": "logo/pgoc-site-logo.png",



    # Links to put along the top menu
    "topmenu_links": [

        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)

    ],



    "custom_links": {

    },

    "hide_models": [
        "amd_processing.datacapturing",
        "amd_processing.dataverification",
        "amd_processing.dataauthentications",

        "main_system_databases.orderdatabase",
        "main_system_databases.flashdeliverydatabase",
        "main_system_databases.pancakephaddressesdatabase",
        "main_system_databases.phaddressdatabase",
        "main_system_databases.islandcategorydatabase",

        "sales.salespersonnel",

        "warehouse.ordersforwarding",
        "warehouse.productstock",

        # add other models you want to hide
        # "auth.user",
        "auth.group",
        "authtoken.token",
        "django_celery_beat.CrontabSchedule",
        "django_celery_beat.ClockedSchedule",
        "django_celery_beat.IntervalSchedule",
        "django_celery_beat.PeriodicTask",
        "django_celery_beat.SolarSchedule"
    ],

    
}
JAZZMIN_SETTINGS["show_ui_builder"] = True

JAZZMIN_UI_TWEAKS = {
    "body_small_text": True,
    "sidebar_nav_flat_style": True,
    "accent": "accent-navy",
    "sidebar": "sidebar-dark-danger",
}


LOGIN_REDIRECT_URL = '/'  # Redirect to home page after login



# SENTRY SDK Configurations
import sentry_sdk

sentry_sdk.init(
    dsn="https://adf1217ec8edbb04d41f805888fc9c84@o4508809836888064.ingest.us.sentry.io/4508809838985216",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for tracing.
    traces_sample_rate=1.0,
    _experiments={
        # Set continuous_profiling_auto_start to True
        # to automatically start the profiler on when
        # possible.
        "continuous_profiling_auto_start": True,
    },
)
