# Generated by Django 5.1.6 on 2025-02-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_fb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chats', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['conversation_id'], name='conv_conversation_id_idx'), models.Index(fields=['customer_id'], name='conv_customer_id_idx'), models.Index(fields=['customer_fb_id'], name='conv_customer_fb_id_idx'), models.Index(fields=['customer_name'], name='conv_customer_name_idx'), models.Index(fields=['page_name'], name='conv_page_name_idx'), models.Index(fields=['status'], name='conv_status_idx')],
            },
        ),
    ]
