# Generated by Django 5.1.6 on 2025-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('page_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('page_category', models.CharField(blank=True, max_length=255, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['page_id'], name='page_page_id_idx'), models.Index(fields=['page_name'], name='page_page_name_idx'), models.Index(fields=['page_category'], name='page_page_category_idx'), models.Index(fields=['page_status'], name='page_status_idx')],
            },
        ),
    ]
