# Generated by Django 5.1.6 on 2025-02-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancake', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
