# Generated by Django 5.1.6 on 2025-02-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancake', '0004_alter_conversations_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_import_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
