# Generated by Django 5.1.6 on 2025-02-19 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancake', '0005_page_is_import_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['worker_id'], name='worker_worker_id_idx'), models.Index(fields=['worker_name'], name='worker_worker_name_idx'), models.Index(fields=['worker_status'], name='worker_status_idx')],
            },
        ),
    ]
