# Generated by Django 5.1.6 on 2025-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancake', '0006_workermonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermonitor',
            name='worker_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='workermonitor',
            index=models.Index(fields=['worker_type'], name='worker_type_idx'),
        ),
    ]
